<?php
$server_name = $_SERVER['SERVER_NAME'];

$file_path = $_SERVER['PHP_SELF'];
echo $file_path;
echo "<br/>".$server_name;
$main_folder = '/home/harbhag/public_html/github/gERP/';
$main_path = 'http://localhost/~harbhag/github/gERP';
$media_folder = '/home/harbhag/public_html/github/gERP/media/';
$media_path = 'http://localhost/~harbhag/github/gERP/media/';
$includes_folder = '/home/harbhag/public_html/github/gERP/includes/';
$includers_path = 'http://localhost/~harbhag/github/gERP/includes/';
$header_footer_folder = '/home/harbhag/public_html/github/gERP/header_footer/';
$header_footer_path = 'http://localhost/~harbhag/github/gERP/header_footer/';
?>
